# .github/workflows/main.yml

name: CI - Build and Test API

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Check out repository
      uses: actions/checkout@v4

    - name: 2. Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: 3. Install dependencies
      run: |
        pip install -r requirements.txt

    - name: 4. Generate data file
      run: |
        # *** THIS STEP IS UPDATED ***
        python -c "from sklearn.datasets import fetch_california_housing; \
        import pandas as pd; \
        housing = fetch_california_housing(); \
        df = pd.DataFrame(data=housing.data, columns=housing.feature_names); \
        df['MedHouseVal'] = housing.target; \
        df.to_csv('data/california_housing.csv', index=False)"

    - name: 5. Train the model
      run: |
        python train.py
        
    - name: 6. Run tests with pytest
      run: |
        pytest